runtime: python37

handlers:
- url: .*
  script: main.app
  secure: always

env_variables:
  SQLALCHEMY_DATABASE_URI: >-
    mysql+pymysql://root:hsangel@/SCANNER?unix_socket=/cloudsql/scan-reponse-co:asia-northeast1:scan-reponse-co

beta_settings:
  cloud_sql_instances: scan-reponse-co:asia-northeast1:scan-reponse-co
